# Hardware Configuration for Multi-Sonicator-IO Web UI
# Based on docs/planning/pin-matrix.md (SOLE SOURCE OF TRUTH)

project:
  name: "multi-sonicator-io"
  description: "Sonicator Multiplexer - Hardware-in-the-Loop Testing"
  version: "1.0.0"

# Device Under Test (ATmega32A)
dut:
  microcontroller:
    type: "ATmega32A-PU"
    package: "DIP-40"
    clock_frequency: 16000000  # 16MHz
    voltage: 5.0
    manufacturer: "Microchip"
  
  # Pin definitions matching your existing types/index.ts
  pins:
    # Port B - Frequency inputs
    PB0: { pin: 1, signal: "FREQ_DIV10_4", direction: "IN", sonicator: 4 }
    PB1: { pin: 2, signal: "FREQ_DIV10_3", direction: "IN", sonicator: 3 }
    PB2: { pin: 3, signal: "FREQ_DIV10_2", direction: "IN", sonicator: 2 }
    PB3: { pin: 4, signal: "FREQ_DIV10_1", direction: "IN", sonicator: 1 }
    PB4: { pin: 5, signal: "FREQ_LOCK_4", direction: "IN", sonicator: 4 }
    PB5: { pin: 6, signal: "FREQ_LOCK_3", direction: "IN", sonicator: 3 }
    PB6: { pin: 7, signal: "FREQ_LOCK_2", direction: "IN", sonicator: 2 }
    PB7: { pin: 8, signal: "FREQ_LOCK_1", direction: "IN", sonicator: 1 }
    
    # Port C - Control outputs
    PC0: { pin: 22, signal: "START_4", direction: "OUT", sonicator: 4 }
    PC1: { pin: 23, signal: "RESET_4", direction: "OUT", sonicator: 4 }
    PC2: { pin: 24, signal: "START_3", direction: "OUT", sonicator: 3 }
    PC3: { pin: 25, signal: "RESET_3", direction: "OUT", sonicator: 3 }
    PC4: { pin: 26, signal: "START_2", direction: "OUT", sonicator: 2 }
    PC5: { pin: 27, signal: "RESET_2", direction: "OUT", sonicator: 2 }
    PC6: { pin: 28, signal: "START_1", direction: "OUT", sonicator: 1 }
    PC7: { pin: 29, signal: "RESET_1", direction: "OUT", sonicator: 1 }
    
    # Port D - Communication and status
    PD0: { pin: 14, signal: "UART_RXD", direction: "IN", function: "MODBUS RTU RX" }
    PD1: { pin: 15, signal: "UART_TXD", direction: "OUT", function: "MODBUS RTU TX" }
    PD2: { pin: 16, signal: "STATUS_LED", direction: "OUT", function: "System status" }
    PD3: { pin: 17, signal: "OVERLOAD_4", direction: "IN", sonicator: 4 }
    PD4: { pin: 18, signal: "OVERLOAD_3", direction: "IN", sonicator: 3 }
    PD5: { pin: 19, signal: "OVERLOAD_2", direction: "IN", sonicator: 2 }
    PD6: { pin: 20, signal: "OVERLOAD_1", direction: "IN", sonicator: 1 }
    PD7: { pin: 21, signal: "AMPLITUDE_ALL", direction: "OUT", function: "Shared amplitude control" }
    
    # Port A - Analog power sensing
    PA4: { pin: 36, signal: "POWER_SENSE_1", direction: "ANALOG", sonicator: 1, scaling: "5.44 mV/W" }
    PA5: { pin: 35, signal: "POWER_SENSE_2", direction: "ANALOG", sonicator: 2, scaling: "5.44 mV/W" }
    PA6: { pin: 34, signal: "POWER_SENSE_3", direction: "ANALOG", sonicator: 3, scaling: "5.44 mV/W" }
    PA7: { pin: 33, signal: "POWER_SENSE_4", direction: "ANALOG", sonicator: 4, scaling: "5.44 mV/W" }

# Test Harness (Arduino Uno R3)
harness:
  type: "Arduino Uno R3"
  microcontroller: "ATmega328P"
  clock_frequency: 16000000
  voltage: 5.0
  
  # Current single-channel prototype connections (Sonicator 4 only)
  connections:
    # MODBUS Communication
    D2: { dut_pin: "PD0", signal: "UART_RXD", direction: "harness_to_dut" }
    D3: { dut_pin: "PD1", signal: "UART_TXD", direction: "dut_to_harness" }
    
    # System monitoring
    D4: { dut_pin: "PD2", signal: "STATUS_LED", direction: "dut_to_harness" }
    
    # Sonicator 4 interface (fully connected)
    D7: { dut_pin: "PB0", signal: "FREQ_DIV10_4", direction: "harness_to_dut", sonicator: 4 }
    D8: { dut_pin: "PB4", signal: "FREQ_LOCK_4", direction: "harness_to_dut", sonicator: 4 }
    A2: { dut_pin: "PD3", signal: "OVERLOAD_4", direction: "harness_to_dut", sonicator: 4 }
    A3: { dut_pin: "PC0", signal: "START_4", direction: "dut_to_harness", sonicator: 4 }
    A4: { dut_pin: "PC1", signal: "RESET_4", direction: "dut_to_harness", sonicator: 4 }
    A1: { dut_pin: "PA7", signal: "POWER_SENSE_4", direction: "dut_to_harness", sonicator: 4 }
    D9: { dut_pin: "PD7", signal: "AMPLITUDE_ALL", direction: "dut_to_harness" }

# Sonicator specifications
sonicators:
  count: 4
  channels:
    - id: 1
      name: "sonicator1"
      db9_connector: "DB9-1"
      power_range: [0, 2000]  # Watts
      frequency_range: [15000, 25000]  # Hz
      amplitude_range: [20, 100]  # Percent
      status: "not_connected"  # Current prototype limitation
      
    - id: 2
      name: "sonicator2"
      db9_connector: "DB9-2"
      power_range: [0, 2000]
      frequency_range: [15000, 25000]
      amplitude_range: [20, 100]
      status: "not_connected"  # Current prototype limitation
      
    - id: 3
      name: "sonicator3"
      db9_connector: "DB9-3"
      power_range: [0, 2000]
      frequency_range: [15000, 25000]
      amplitude_range: [20, 100]
      status: "not_connected"  # Current prototype limitation
      
    - id: 4
      name: "sonicator4"
      db9_connector: "DB9-4"
      power_range: [0, 2000]
      frequency_range: [15000, 25000]
      amplitude_range: [20, 100]
      status: "connected"  # Fully connected in current prototype

# Communication settings
communication:
  modbus:
    slave_id: 2
    baud_rate: 115200
    data_bits: 8
    stop_bits: 1
    parity: "none"
    timeout_ms: 1000
    
  serial:
    port: "/dev/ttyUSB0"  # Default, configurable
    baud_rate: 115200
    timeout_ms: 5000

# Test capabilities
test_capabilities:
  - name: "modbus_communication"
    description: "MODBUS RTU protocol testing"
    pins: ["PD0", "PD1"]
    supported: true
    
  - name: "sonicator_4_control"
    description: "Complete sonicator 4 testing"
    pins: ["PB0", "PB4", "PD3", "PC0", "PC1", "PA7", "PD7"]
    supported: true
    
  - name: "power_measurement"
    description: "Power sensing validation"
    pins: ["PA7"]
    supported: true
    
  - name: "amplitude_control"
    description: "PWM amplitude control"
    pins: ["PD7"]
    supported: true
    
  - name: "safety_interlocks"
    description: "Safety system testing"
    pins: ["PC0", "PC1", "PD3"]
    supported: true
    
  - name: "multi_channel_testing"
    description: "All 4 sonicator channels"
    pins: ["all"]
    supported: false  # Future expansion
    note: "Requires 4-channel harness expansion"

# Hardware limitations
limitations:
  current_prototype: "Single-channel HIL harness"
  supported_channels: [4]
  unsupported_channels: [1, 2, 3]
  expansion_notes: "Channels 1-3 require additional harness connections"
  
# Environment settings
environment:
  simulation_mode: true  # Default to simulation
  hardware_timeout_ms: 5000
  command_timeout_ms: 1000
  log_level: "info"
