# Example Performance Benchmarking Configuration

project_type: "platformio"  # Options: platformio, cmake, npm, python, generic

build:
  environments:
    - "test_desktop"
    - "development"
    - "production"
  iterations: 3
  clean_build: true
  parallel_jobs: 4

test:
  iterations: 3
  timeout: 300
  parallel: true

monitoring:
  sample_interval: 1.0
  memory_threshold: "512MB"
  cpu_threshold: 80

thresholds:
  build_time_warning: 120   # seconds
  build_time_error: 300
  test_time_warning: 60
  test_time_error: 180

# Project-specific overrides
project:
  name: "Example Project"
  version: "1.0.0"
  type: "embedded"