# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# File: Axovia Flow™ Extension Configuration
# Author: Stephen Boyett
# Company: Axovia AIå
# Version: 1.0
# @brief: Axovia Flow™ Config File intended 
#           to extend The BMad Core config
# Date: 2025-09-07
# _____________________________________________

extension:
  name: "Axovia Flow™"
  version: "1.0"
  description: "Agentic workflow orchestration and multi-agent collaboration extension"

# Agent Command Extensions
agent_extensions:

  # Project Manager Agent Extension
  pm:
    additional_commands:
      - "create-feature-spec: run task create-feature-spec.md with template feature-spec-tmpl.yaml"
    additional_dependencies:
      tasks:
        - create-feature-spec.md
      templates:
        - feature-spec-tmpl.yaml

  # Product Owner Agent Extension
  po:
    additional_commands:
      - "create-feature-spec: run task create-feature-spec.md with template feature-spec-tmpl.yaml"
      - "validate-feature-spec: validate feature specification against company standards"
    additional_dependencies:
      tasks:
        - create-feature-spec.md
      templates:
        - feature-spec-tmpl.yaml

  # Scrum Master Agent Extension
  sm:
    additional_commands:
      - "create-stories-from-feature: create stories from feature specification"
      - "create-implementation-plan: create an implementation plan from a feature specification"
    additional_dependencies:
      tasks:
        - create-stories-from-feature.md
        - create-implementation-plan.md
      templates:
        - .bmad-core/templates/story-tmpl.yaml
        - implementation-plan-tmpl.yaml

agile:
  fileLocations:
    stories: "docs/agile/stories"
    features: "docs/agile/features"
    epics: "docs/agile/epics"
    prd: "docs/prd.md"
    architecture: "docs/architecture.md"
    prd-shards: "docs/prd-shards"

# Company wide Software SOPs 
 

standard_operating_procedures:
  # **IMPORTANT:** Always adhere to these procedures above all else

   # SOPs for Planning related Tasks
  - planning: 
    feature_specification: ".axovia-flow/company-standards/feature-specification.md"
    implementation_plan: ".axovia-flow/company-standards/implementation-plan.md"
    definition_of_done: ".axovia-flow/company-standards/planning-definition-of-done.md"

  # SOPs for Quality Assurance Related Tasks
  - quality:
    repository_audit: ".axovia-flow/company-standards/repository-audit.md"
    security_audit: ".axovia-flow/company-standards/security-audit.md"
    pull_request: ".axovia-flow/company-standards/pull-request.md"
    code_review: ".axovia-flow/company-standards/code-review.md"

  # SOPs for Testing Related Tasks
  - testing:
    sw_testing_global: ".axovia-flow/company-standards/global-testing-sop.md"
    
  # SOPs for Release Related Tasks
  - release: 
    release_report: ".axovia-flow/company-standards/release-format.md"
  
  # SOPs for Project Structure and Management
  - repository_management: 
    makefile_standard: ".axovia-flow/company-standards/makefile-standard.md"
    root_directory: ".axovia-flow/company-standards/root-directory.md"
    project_structure: ".axovia-flow/company-standards/project-structure.md"
    
  # SOPs for Project Implementation Phase and General Software Development 
  - development: 
    definition_of_done: ".axovia-flow/company-standards/planning-definition-of-done.md"
    coding-style: ".axovia-flow/company-standards/coding-style.md"
    communication: ".axovia-flow/company-standards/communication.md"

  # SOPs that are to be deprecated upon the completion of the Axovia Flow™ Framework
  - deprecated:
    # DEPRECATION REASON: >> File Based Agent Sync, will be outperformed by Axovia Flow™ Agent Orchestration.
    multi_agent_collaboration: ".axovia-flow/company-standards/multi-agent-collaboration.md"


# Feature Specification Configuration
feature_specifications:
  location: "docs/agile/features"
  template: "feature-spec-tmpl.yaml"
  naming_convention: "feature-{id}-{name-kebab-case}.md"
  id_format: "FR-{###}"
  standard_file: ".axovia-flow/company-standards/feature-specification.md"

# Custom Tasks
tasks:
  create_feature_spec:
    file: ".axovia-flow/tasks/create-feature-spec.md"
    description: "Create comprehensive feature specifications following company standards"
    agents: ["pm", "po"]
    requires_interaction: true
    template: "feature-spec-tmpl.yaml"

  create_stories_from_feature:
    file: ".axovia-flow/tasks/create-stories-from-feature.md"
    description: "Create stories from feature specification"
    agents: ["sm"]
    requires_interaction: true
    template: "feature-spec-tmpl.yaml"

  create_implementation_plan:
    file: ".axovia-flow/tasks/create-implementation-plan.md"
    description: "Create implementation plans with visual checklists separated by story"
    agents: ["sm"]
    requires_interaction: true
    template: "implementation-plan-tmpl.yaml"

# Custom Templates
templates:
  feature_spec:
    file: ".axovia-flow/templates/feature-spec-tmpl.yaml"
    description: "Feature specification template following Axovia AI standards"
    output_location: "docs/agile/features"

  implementation_plan:
    file: ".axovia-flow/templates/implementation-plan-tmpl.yaml"
    description: "Implementation plan template with visual checklists by story"
    output_location: "docs/planning"

# Quality Standards
standards:
  feature_specification: ".axovia-flow/company-standards/feature-specification.md"
  
# Quality Gates
quality_gates:
  feature_specification:
    - "All mandatory sections completed"
    - "Scope clearly defined with inclusions/exclusions" 
    - "Acceptance criteria are measurable and testable"
    - "Traceability established to source requirements"
    - "Compliance with company standard verified"

# Integration Settings
integration:
  # Configuration files to load and integrate
  bmadCoreConfigFile: ".bmad-core/core-config.yaml"
  axoviaFlowConfigFile: ".axovia-flow/flow-config.yaml"

  # Configration files loaded after other config files should: 
  # - First extend complimenting configuration
  # - Second override any conflicting configuration 
  ##### If there are any conflicting configurations the agent should immediatly alert the user after initialization!!! 
  ## index 0 is the lowest priority configuration and should be extended and conflicts overriden by following config
  config_load_order: [integration.bmadCoreConfigFile, integration.axoviaFlowConfigFile]
  use_bmad_config: true
  extends_bmad_core: true
  uses_core_elicitation: true
  custom_elicitation_methods: []
  
# File Locations
fileLocations:
  tasks: ".axovia-flow/tasks"
  templates: ".axovia-flow/templates"
  standards: ".axovia-flow/company-standards"
  prd:
    file: "docs/prd.md"
    shards: "docs/prd-shards"    
  architecture:
    overview: "docs/architecture.md"
    shards: "docs/architecture/shards"
  features: "docs/agile/features"
  stories: "docs/agile/stories"
  epics: "docs/agile/epics"
  qa: "docs/qa"


keywords:
  - word: "agent-id"
    definition: "A Unique Identifie to identify a specific agent instance.  The Agent ID is formatted as `[AGENT-TYPE]-[INSTANCE-NUMBER]`.  For example: `[DEV-01]` is the first instance of the `DEV` agent."
  - word: "standalone-agent"
    definition: "An agent that performs specific tasks and is not currently acting as one of the pre-defined official axovia-flow agents. Common standalone agents: cascade, augment, claude, cursor, augment-01, cascade-ui"
  - word: "multi-agent-collaboration"
    definition: "An official axovia-flow agent protocol that defines how agents coordinate and collaborate within an axovia-flow project when multiple agents are working together or in parallel.
  - word: "acceptance-test"
    definition: "A Behave Driven test that validates PRD requirements using BDD formats with specific pre-defined Gherkin Scenarios that map to the PRD Requirements for the given project."
  - word: "functionality-report"
    definition: "A report that is included with every company project that followed the functionality-report standard of procedure. This report is generated on CI Release and is packaged in a specific way so that the information can be displayed to the executives."
  - word: "executive-report"
    definition: "An optional markdown formatted report that is included in the release alongside the functionality-report. This report can be miscellaneous extra information about the projects functionality that is not included in the functionality-report.  Explanations for test coverage gaps, or any other piece of information that should be exposed at the project management level"
  - word: "agent-report"
    definition: "A report generated by an agent that is stored in the `docs/agent-reports/` directory.  *NOTE: Refer to the README.md in the `docs/agent-reports/` directory for more information.*"
