# Company Standards Configuration
# Configure the source repository for company standards

# Remote repository settings (when available)
remote:
  enabled: true
  owner: "Axovia-AI"           # GitHub organization/user
  repository: "axovia-flow"    # Repository name
  branch: "main"               # Branch to sync from
  source_path: "docs/standards" # Path within repository
  
# Local fallback settings
local:
  enabled: true                # Enable local fallback when remote unavailable
  source_path: "docs/standards" # Local path to standards
  
# Target settings
target:
  path: ".axovia-flow/company-standards"  # Where to store standards locally
  
# Sync behavior
sync:
  auto_fallback: true          # Automatically use local if remote fails
  preserve_local_changes: false # Whether to preserve local modifications
  backup_before_sync: false    # Create backup before overwriting
  
# Standards validation
validation:
  required_files:              # Files that must exist
    - "coding-style.md"
    - "project-structure.md"
    - "sw-testing-standard.md"
  
  optional_files:              # Files that are nice to have
    - "pull-requests.md"
    - "release-format.md"
    - "root-directory.md"
