<!-- ~* Axovia Flow™ Framework ~* -->
---
# File: Axovia Flow™ Service Configuration
# Author: Stephen Boyett
# Company: Axovia AI
# Version: 1.0
# @brief: Service configuration for Axovia Flow™ services
# Date: 2025-09-11
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Service Configuration
services:
  # Orchestrator Service Configuration
  orchestrator:
    host: "localhost"
    port: 8080
    log_level: "INFO"
    shutdown_timeout: 30
    
  # Director of Flow Service Configuration
  director:
    host: "localhost"
    port: 8081
    log_level: "INFO"
    shutdown_timeout: 30
    
  # MCP Server Configuration
  mcp_server:
    host: "0.0.0.0"
    port: 8000
    log_level: "INFO"
    shutdown_timeout: 30
---
