services:
  simulavr-build:
    build:
      context: ../../
      dockerfile: tools/simulavr/Dockerfile.optionA
    volumes:
      - ../../:/workspace
    working_dir: /workspace
    command: >-
      bash -lc "set -euo pipefail &&
      ([ -d simulavr ] || git clone https://git.savannah.nongnu.org/git/simulavr.git) &&
      cd simulavr &&
      sed -i 's/^add_subdirectory(\\s*debian\\s*)/# add_subdirectory(debian)/' CMakeLists.txt || true &&
      rm -rf build &&
      cmake -S . -B build -DBUILD_PYTHON=ON -DCMAKE_BUILD_TYPE=Release &&
      cmake --build build -j\$(nproc) &&
      python3 - <<'PY'
      import sys, glob, os
      cands = glob.glob('build/pysimulavr/*pysimulavr*.so') or glob.glob('build/*pysimulavr*.so')
      assert cands, 'pysimulavr .so not found'
      sys.path.insert(0, os.path.dirname(cands[0]))
      import pysimulavr
      print('pysimulavr OK at', cands[0])
      PY
      "

