# CI Workflow Template (GitHub Actions)
# Renders to .github/workflows/ci.yml

name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "{{python_version}}"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          if [ -f pyproject.toml ]; then pip install -e .[test] || true; fi

      - name: Validate configs
        run: |
          make validate-configs || (echo "Config validation failed" && exit 1)

      - name: Lint & Format Check
        run: |
          make check-lint-deps check-format-deps
          flake8 --version
          mypy --version
          black --version
          make lint

      - name: Run Tests
        env:
          PYTHONPATH: src
        run: |
          make test-unit
          make test-integration
          make test-acceptance

      - name: Upload Coverage (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: reports/coverage/
