name: Simple CI Pipeline

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc g++ lcov
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r config/requirements-testing.txt
        
    - name: Install PlatformIO
      run: |
        pip install platformio
        
    - name: Run CI Pipeline
      run: |
        make ci
        
    - name: Upload CI reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ci-reports
        path: |
          coverage/
          final/
        retention-days: 30
        
    - name: Verify pipeline success
      run: |
        if [ -f "final/executive-report.json" ] && [ -f "final/coverage-summary.json" ]; then
          echo "✅ CI Pipeline completed successfully"
          echo "📊 Executive report and coverage summary generated"
        else
          echo "❌ CI Pipeline failed - missing required reports"
          exit 1
        fi